// 작성자: 구현우

export const Technologies = {
  AWS: {
    name: "AWS",
    logo: "AmazonAWS",
    backColor: "232F3E",
    color: "white",
  },
  C: {
    name: "C",
    logo: "C",
    backColor: "A8B9CC",
    color: "white",
  },
  CPP: {
    name: "C++",
    logo: "c%2B%2B",
    backColor: "00599C",
    color: "white",
  },
  CSS: {
    name: "CSS3",
    logo: "CSS3",
    backColor: "1572B6",
    color: "white",
  },
  CSHARP: {
    name: "Csharp",
    logo: "CSHARP",
    backColor: "239120",
    color: "white",
  },
  DJANGO: {
    name: "Django",
    logo: "Django",
    backColor: "092E20",
    color: "white",
  },
  DOCKER: {
    name: "DOCKER",
    logo: "DOCKER",
    backColor: "2496ED",
    color: "white",
  },
  FIGMA: {
    name: "FIGMA",
    logo: "FIGMA",
    backColor: "F24E1E",
    color: "white",
  },
  FLASK: {
    name: "FLASK",
    logo: "FLASK",
    backColor: "000000",
    color: "white",
  },
  GIT: {
    name: "GIT",
    logo: "GIT",
    backColor: "F05032",
    color: "white",
  },
  GO: {
    name: "GO",
    logo: "GO",
    backColor: "00ADD8",
    color: "white",
  },
  HTML: {
    name: "HTML5",
    logo: "HTML5",
    backColor: "E34F26",
    color: "white",
  },
  JAVASCRIPT: {
    name: "JavaScript",
    logo: "Javascript",
    backColor: "F7DF1E",
    color: "black",
  },
  JAVA: {
    name: "JAVA",
    logo: "Java",
    backColor: "007396",
    color: "white",
  },
  KOTLIN: {
    name: "KOTLIN",
    logo: "KOTLIN",
    backColor: "7F52FF",
    color: "white",
  },
  KUBERNETES: {
    name: "KUBERNETES",
    logo: "KUBERNETES",
    backColor: "326CE5",
    color: "white",
  },
  MYSQL: {
    name: "MYSQL",
    logo: "MYSQL",
    backColor: "4479A1",
    color: "white",
  },
  NEXTJS: {
    name: "NEXTJS",
    logo: "NEXT.JS",
    backColor: "000000",
    color: "white",
  },
  PYTHON: {
    name: "Python",
    logo: "Python",
    backColor: "3776AB",
    color: "white",
  },
  REACT: {
    name: "React",
    logo: "React",
    backColor: "61DAFB",
    color: "white",
  },
  SQL: {
    name: "SQL",
    logo: "SQLite",
    backColor: "003B57",
    color: "white",
  },
  SWIFT: {
    name: "SWIFT",
    logo: "SWIFT",
    backColor: "F05138",
    color: "white",
  },
  SPRING: {
    name: "Spring",
    logo: "Spring",
    backColor: "6DB33F",
    color: "white",
  },
  SPRINGBOOT: {
    name: "SpringBoot",
    logo: "SpringBoot",
    backColor: "6DB33F",
    color: "white",
  },
  SVELTE: {
    name: "SVELTE",
    logo: "SVELTE",
    backColor: "FF3E00",
    color: "white",
  },
  TYPESCRIPT: {
    name: "TypeScript",
    logo: "TypeScript",
    backColor: "3178C6",
    color: "white",
  },
  VUE: {
    name: "Vue",
    logo: "Vue.js",
    backColor: "4FC08D",
    color: "white",
  },
};
